/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_btr_proxy_search_desktop_gnome_ProxySchemasGSettingsAccess */

#ifndef _Included_com_btr_proxy_search_desktop_gnome_ProxySchemasGSettingsAccess
#define _Included_com_btr_proxy_search_desktop_gnome_ProxySchemasGSettingsAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_btr_proxy_search_desktop_gnome_ProxySchemasGSettingsAccess
 * Method:    getValueByKeyBySchema
 * Signature: ()Ljava/util/Map;
 */
JNIEXPORT jobject JNICALL Java_com_btr_proxy_search_desktop_gnome_ProxySchemasGSettingsAccess_getValueByKeyBySchema
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
